version: "3.9"
services:
#    web:
#        build: .
#        ports:
#            - "5000:5000"
#        volumes:
#            - .:/code
#            - logvolume01:/var/log
#        links:
#            - redis
  redis:
    image: redis:6.2
    restart: always
    ports:
      - "6379:6379"
  postgres:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "media"
