version: "3.9"
services:
  redis:
    image: redis:6.2
    restart: always
    ports:
      - "6379:6379"
  postgres:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "media"
    volumes:
    - ./db:/var/lib/postgresql/data
